[project]
name = "kis-final"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.2",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
